# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=30)),
                ('Password2', models.CharField(max_length=30)),
            ],
        ),
    ]
