# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('thali', models.IntegerField()),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
