# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_ordermeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermeal',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ordermeal',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermeal',
            name='mobile',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ordermeal',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ordermeal',
            name='thali',
            field=models.IntegerField(blank=True),
        ),
    ]
