# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
