# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
