# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180828_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.NullBooleanField(default=None),
        ),
    ]
