# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='Cook',
        ),
    ]
